version: 0.2

phases:
  install:
    commands:
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - apt-get update
      - echo '-k' > ~/.curlrc
  pre_build:
    commands:
      - echo "Setting Date Modified"
      - cd component-library/src/assets
      - export LAST_MODIFIED_DATE=$(date -u +"%Y-%m-%d")
      - echo $LAST_MODIFIED_DATE
      - printf "{\"LASTDATEMODIFIED\":\"$LAST_MODIFIED_DATE\"}" >| date-modified.json
      - echo `cat date-modified.json`
      - cd ..
      - cd ..
      - cd ..
      - echo installing dependencies...
      - n 16.16.0
      - npm i -g @angular/cli@14.1.3
      - npm run install
      # - npm run cypress:run:quick
  build:
    commands:
      - npm run deploy-build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: component-library/dist/demo-project

cache:
  paths:
    - "/root/.npm/**/*"
    - "node_modules/**/*"