version: 0.1

phases:
  install:
    commands:
      - apt-get update
      - echo '-k' > ~/.curlrc
  pre_build:
    commands:
      - echo installing dependencies...
      - n 16.16.0
      - npm i -g @angular/cli@14.1.3
      - npm ci --prefix ./component-lib
      # - npm run cypress:run:quick
  build:
    commands:
      - ng build ircc-ds-angular-component-library
      - npm ci
      - ng build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/demo-project

cache:
  paths:
    - "/root/.npm/**/*"
    - "node_modules/**/*"
