#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
RED='\033[0;31m'
NC='\033[0m' # No Color

if [ -z "${AWS_ACCESS_KEY_ID}" ]; then
    echo "${RED}Please set your AWS Credentials${NC}"
    exit 1
fi
