1 name: Deploy CDK Project
2 on:
3  push:
    paths:
      - form-backend/**
 jobs:
  aws_cdk:
  if: github.event_name == 'push'
    runs-on: ubuntu-latest
   steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      working-directory: ./subdirectory

    - name: cdk diff
       uses: youyo/aws-cdk-github-actions@v2
        with:
         cdk_subcommand: 'diff'
         actions_comment: true
       env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ./subdirectory
        
     - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: '*'
         cdk_args: '--require-approval never'
         actions_comment: false
         env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./subdirectory